url: "https://yello.ooo"
title: "yello.ooo"
tagline: "it's like a trash compactor for your soul."

exclude:
  - .idea/
  - .git/
  - .gitignore
  - .gitmodules
  - README.md
collections:
  posts:
    permalink: /blog/:title
  projects:
    permalink: /:collection/:title/
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]